skinparam SequenceBoxFontName MesloLGS NF
skinparam ParticipantFontName MesloLGS NF
skinparam ArrowFontName MesloLGS NF
skinparam BoxFontName MesloLGS NF
skinparam NoteFontName MesloLGS NF
skinparam ActivityFontName MesloLGS NF
skinparam DefaultFontName MesloLGS NF