@startuml linux-syscalls

skinparam linetype ortho
!theme toy
'top to bottom direction
'skinparam nodesep 36
'skinparam ranksep 50

left to right direction

together {
    rectangle "\t\t\t\t\t\tuser space\t\t\t\t\t\t\t" as uspace {
        rectangle "Applications/Processes" as apps
    }

    rectangle "syscalls" as syscalls {
        collections "execve()\t  tread()\twrite()\tclose()\tsend()\trecv()\taccept()  " as calls
    }
    rectangle "\t\t\t\t\t\tkernel space\t\t\t\t\t\t\t" as kspace {
        rectangle "Linux Kernel" as kernel
    }

    rectangle "\\t\t\t\t\t\thardware\t\t\t\t\t\t\t" as hardware {
        left to right direction
        rectangle "CPU\t| memory | devices" as cpu
    }
}
hardware <-> kspace
kernel <-> syscalls
uspace <-> calls
'uspace --[hidden]-> kernel

'cpu -[hidden]-> memory
'memory -[hidden]-> devices


@enduml