@startmindmap k8s-config-mindmap
'Imports
!define SPRITES https://raw.githubusercontent.com/Piotr1215/sprites/master
'Icons
!include <logos/azure.puml>
!include <logos/google-cloud.puml>
!include <logos/linode.puml>
!include <logos/aws.puml>
'!include SPRITES/logo-alibaba.puml
!include <logos/ibm.puml>
<style>
mindmapDiagram {
    node {
        BackgroundColor white
        LineColor green
    }
    rootNode {
        LineStyle 8.0;3.0
        LineColor blue
        BackgroundColor white
        LineThickness 1.0
        RoundCorner 35
        Shadowing 0.0
        FontStyle bold
    }
}
</style>

* Public Cloud\n   Providers
** Microsoft Azure\n      <$azure>
** Google Cloud Platform\n            <$google-cloud>
left side
** Amazon Web Services\n             <$aws>
left side
'** IBM Cloud\n  <$ibm*0.5>
'** Alibaba Cloud\n     <$alibaba_logo*0.5>
'** Linode\n<$linode>

@endmindmap