@startmindmap
<style>
mindmapDiagram {
    node {
        BackgroundColor #f3807b
        LineColor green
    }
    :depth(1) {
      BackGroundColor #fdcd3c
      LineColor blue
      LineThickness 1.0
      RoundCorner 35
      Shadowing 0.0
      FontStyle bold
    }
    :depth(2) {
      BackGroundColor #fdcd3c
      LineColor black
      LineThickness 1.0
      RoundCorner 35
      Shadowing 0.0
    }
}
</style>
* Upbound
left
** Enterprise\n Products
*** [[https://github.com/upbound/universal-crossplane Universal Crossplane]]
**** Distribution of Crossplane
**** Feature parity with Crossplane
**** Integrated with the CLI
**** Stable 18 month version support
**** Enables connectivity to UC
**** Language server integration
*** Cloud
*** Registry/Marketplace
**** React frontent
**** Artefacts
***** Providers
***** Configurations
*** CLI
**** Go
**** up
right
** Crossplane\n     OOS
*** Open Source
*** Kubernetes Addon
*** Control Plane
*** API Centric
*** Provider Types
**** Regular Provider
*****_ [[https://github.com/crossplane/crossplane/blob/master/docs/contributing/provider_development_guide.md Documentation]]
*****_ [[https://github.com/crossplane/provider-template Template]] 
**** Terrajet Provider
*****_ [[https://github.com/crossplane/terrajet/blob/main/docs/generating-a-provider.md Documentation]]
*****_ [[https://github.com/crossplane-contrib/provider-jet-template Template]] 
**** Tools
***** [[https://github.com/crossplane/crossplane-tools/blob/master/README.md Angryjet]]
*****_ Adds Crossplane required scaffold to resource kinds
*** Managed Infrastructure
**** Configuration resource
***** Managed Resource
******_ Cluster scoped
******_ High fidelity
******_ Represent resource in extenrnal system
******_ Defined by provider
***** Provider
****** Enable access to extenrnal system
*******_ Kubernetes secret
*******_ Other metadata
******_ Cluster scoped
******_ ProviderConfig resource
**** Controller
*****_ Watches for changes in managed resources (CRUD)
*****_ Calls provider API as a response to the change
*****_ Matches actual state to desired state
@endmindmap
