@startuml AAA
'listopeniconic
'stdlib
!include <aws/Compute/AmazonECS/ECScontainer/ECScontainer>
!include <aws/Compute/AmazonECS/ECScontainer_Alt1/ECScontainer_Alt1>
!include <aws/Compute/AmazonECS/ECScontainer_Alt2/ECScontainer_Alt2>
rectangle "<$ECScontainer>\nRegular"
rectangle "<$ECScontainer_Alt1>\nAlt 1"
rectangle "<$ECScontainer_Alt2>\nAlt 2"
@enduml
