@startuml azure-aci-architecture
!define TITLE Arure Container Instances Architecture

!include <tupadr3/devicons/chrome>

!include <aws/Compute/AmazonECS/ECScontainer/ECScontainer>

!include <tupadr3/font-awesome-5/memory>

!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/release/2-1/dist
!include AzurePuml/AzureCommon.puml
!include AzurePuml/Compute/all.puml
!include AzurePuml/Containers/all.puml
!include AzurePuml/Storage/AzureFileStorage.puml
!include AzurePuml/Networking/AzureDNS.puml

'!includeurl AzurePuml/AzureSimplified.puml

'Global Styles
!include https://raw.githubusercontent.com/Piotr1215/dca-prep-kit/master/diagrams/styles.iuml
skinparam monochrome false
skinparam rectangleBackgroundColor white
skinparam RectangleBorderThickness<<contianer>> 0
skinparam rectangleBorderStyle default
skinparam Linetype polyline
left to right direction

AzureVirtualMachine(vm, "Azure VM", "VM"){
    rectangle "<color:AZURE_SYMBOL_COLOR><$AzureDNS>\nPublic IP" as dns

    rectangle "Container Group" as cgroup {
        rectangle "<color:AZURE_SYMBOL_COLOR><$ECScontainer>\napp:v1" <<contianer>> as con1
        rectangle "<color:AZURE_SYMBOL_COLOR><$ECScontainer>\nsidecar:v2" <<contianer>> as con2
        AzureFileStorage(fstore1, "File Share", "mounted: /data/appdata")
        AzureFileStorage(fstore2, "File Share", "mounted: /data/config")
        rectangle "<color:AZURE_SYMBOL_COLOR><$memory>\nTemporary in-memroy storage" as fsecret
    }
}
rectangle "<$chrome>" as browser

con1 -- fstore1
con2 -- fstore2
con2 -- fsecret

con1 --- con2 : http://localhost

browser -- dns: HTTPS
dns -- con1


@enduml