@startuml azure-ci-cd


box "Continous Integration"
"Source Code" ->  : Build
"Source Code" -> CI : Test
"Source Code" -> CI : Merge
end box
Test -> Merge
Merge -> Artifacts : Release
Artifacts -> Hosting : Deploy
@enduml