@startuml control-plane-sequence
!pragma teoz true
!theme mars
hide footbox
autonumber

scale 1920x1080
skinparam defaultTextAlignment center
skinparam NoteTextAlignment left
skinparam shadowing false
skinparam backgroundColor transparent
skinparam BoxPadding 10

title Kubernetes as Control Plane for Infrastructure Provisioning

actor Developer as dev
box "\nDevelopment" 
  participant "IDP Portal" as port
  dev -> port : Self service app and infrastructure
  note right of port : Developer accesses through Port\nfor unified UI experience
end box

actor "Platform Engineer" as pe
box "\nKubernetes Cluster" 
    participant "ArgoCD" as argo
    participant "Crossplane" as crossplane
    control "Kubernetes" as K8sAPI
end box

box "\nGitOps" 
participant "GitOps Repository" as git
      port -> "Pull Request" ** : Push changes to remote
      "Pull Request" <- pe : Approve and merge changes and update configurations
      git --> argo : Sync changes to ArgoCD
      argo -> K8sAPI : Deploy changes to Kubernetes
      K8sAPI -[#blue]-> K8sAPI : Kubernetes API reconciles infrastructure via Crossplane
      [<- crossplane : Provision infrastructure via providers
end box

@enduml
