@startuml docker-engine
'Icons
!include <tupadr3/devicons/linux>
!include <tupadr3/devicons/docker>
!include <tupadr3/font-awesome/terminal>
'Global Styles
!include https://raw.githubusercontent.com/Piotr1215/dca-prep-kit/master/diagrams/styles.iuml

storage "<$terminal>\ndocker CLI" {
    storage "REST API" {
        storage "        <$docker>\n        server\ndocker daemon" {

        }
    }
}
@enduml