@startuml docker-architecture
'Icons
!include <tupadr3/devicons/linux>
!include <tupadr3/devicons/docker>
'Global Styles
!include styles.iuml

rectangle "                      <$docker>\n High Level docker Architecture"

package "<$docker> Docker" as runtime {

    component "Docker CLI" as dockercli
    component "REST API" as restapi

    dockercli <--> restapi
    node "Docker Deamon" as dockerdeamon {
        [Images]
        [Volumes]
        [Networks]
    }
    restapi <--> dockerdeamon
    component libcontainer
    dockerdeamon <-[hidden]-> libcontainer

    node containerd {
        [Manage Containers]
    }
    node runC {
        [Run Containers]
    }

    dockerdeamon --- containerd
    containerd --- runC
}

package "<$linux> Linux" as linux {
    component "namespace"
    component "CGroups"
}

libcontainer - linux

@enduml
