@startmindmap docker-security
'Icons
!include <tupadr3/devicons/linux>
!include <cloudinsight/docker>
!include <tupadr3/material/error>
!include <tupadr3/material/security>
!include <tupadr3/material/perm_identity>
!include <tupadr3/font-awesome/check>
'Global Styles
!includeurl https://raw.githubusercontent.com/Piotr1215/dca-prep-kit/master/diagrams/styles.iuml

* Docker Security\n        <$security>
** Theats\n<$error>
*** Remove volumes
*** Run unauthorized containers
*** Gain root access to the system
*** Manupilate network and network devices
** Remedies\n  <$check>
*** Access to Host\n      <$linux>
**** Disable Password Based Authentication
**** Enable SSH only access
**** Apply minimum required access policy
*** Authentication\n       <$perm_identity>
**** Encrypt access to docke host from CLI
**** Set **tlsverify** to true in daemon.json
**** Distribute certificates to trusted clients
@endmindmap
