@startuml docker-components

rectangle "                                  <$docker>\n Components For Running Docker Containers" as tit

!include <cloudinsight/docker>
!include <cloudinsight/linux>
!include styles.iuml

together "Group" as grp {
    package "Docker Runtime" as runtime {
        component "namespaces"
        component "CGroupss"

    }

    package "<$registry> Linux" as linux {
        component "namespace"
        component "CGroups"
    }
}

tit -[hidden]-> grp
@enduml
