@startuml docker-lifecycle
'!theme bluegray
'!theme crt-amber
'!theme crt-green

!theme plain

scale 1920x1080

skinparam SequenceBoxFontName MesloLGS NF
skinparam ParticipantFontName MesloLGS NF
skinparam ArrowFontName MesloLGS NF
skinparam BoxFontName MesloLGS NF
skinparam NoteFontName MesloLGS NF

!include https://raw.githubusercontent.com/Piotr1215/dca-prep-kit/master/diagrams/MesloLGS.iuml

box "Development"
participant "Dockerfile" as file
file -> local: Run and test locally
end box

box "Build & Ship"
participant "Git Repository" as repo
file -> repo : Push
CI <- repo : Trigger Build
group Continous Integration
    CI -> CI: Source code scanning
    CI -> CI: Run automated tests
    CI -> CI: Build Image
    CI -> CI: Image scannning
end
CD -> registry: Push Image
participant "Contianer Registry" as registry
end box

box "Operations"
participant Docker as host
host -> registry: Pull image
host -> host : Run contianer
host -> Medium : Serve content
note right of Medium
    Medium can be a web page running docker or
    an on pre installation of a service
    or a cron job on a server etc.
end note
host -> Logs: Observability
host -> Portainer: Manage containers
note right of Portainer
    Containers can be managed with portainer either
    on prem or remotely (for example Azure Container Instances)
end note
end box
@enduml