@startuml k8s-storage-seq
'Icons
!include <kubernetes/k8s-sprites-labeled-25pct>
!include <aws/Compute/AmazonECS/ECScontainer/ECScontainer>
!include <tupadr3/font-awesome-5/user>
'Global Styles
'!include https://raw.githubusercontent.com/Piotr1215/dca-prep-kit/master/diagrams/styles.iuml
skinparam BackgroundColor white
skinparam componentShadowing true
skinparam rectangleRoundCorner 0
skinparam rectangleBorderStyle default
skinparam rectangleBackgroundColor white
skinparam componentBackgroundColor white
skinparam linetype poly
skinparam rectangleShadowing true
skinparam ActorBackgroundColor white
skinparam ParticipantBackgroundColor lightblue
skinparam ArrowColor black
'skinparam monochrome false
!define TITLE Kubernetes PV and PVC Lifecycle

title TITLE

actor "Admin" as admin #green
participant "Persistent Volume" as pv

==Creation==
admin -> pv : Creates
activate pv #lightgray
note left of pv : Backed by phisical storage
actor "Developer" as dev #gray
participant "Persistent Volume Claim" as pvc
dev -> pvc : Creates
activate pvc #lightgray

==Setup==
pv <- pvc : Claims
pvc -> pvc : Checks pv availability

==Usage==
pvc -> pod : Mounted to
pvc -> pvc : Set to bound
pod <- containers : Use mounted\nvolumes

==Cleanup==
dev -> pvc:  Deletes PVC
destroy pvc
group Reclaiming Policies
    else Retain

    pv --> pv : PV Remains available

    else Recycle
    note right
        Warning: The Recycle reclaim policy is deprecated.
        Instead, the recommended approach
        is to use dynamic provisioning.
    end note

    pv --> pv: PV Data is scrubbed, but \nremains available

    else Delete
    pv -[#red]-> pv : PV is automatically removed\ndata lost
    destroy pv
end

@enduml