@startuml k8s-config-components
'Icons
!include <kubernetes/k8s-sprites-labeled-25pct>
!include <aws/Compute/AmazonECS/ECScontainer/ECScontainer>
!include <tupadr3/font-awesome-5/user>
'Global Styles
'!include https://raw.githubusercontent.com/Piotr1215/dca-prep-kit/master/diagrams/styles.iuml
skinparam componentShadowing true
skinparam rectangleRoundCorner 0
skinparam rectangleBorderStyle default
skinparam rectangleBackgroundColor white
skinparam componentBackgroundColor white
skinparam linetype poly
skinparam rectangleShadowing true
'skinparam monochrome false
!define TITLE Kubernetes Pod Configuration

title TITLE
rectangle "<$pod>" as pod

rectangle "<$pod>\nPod" as pod
rectangle "containers:" as containers {
        rectangle "     <$ECScontainer>\n Contianer 1" as cont1
        rectangle "     <$ECScontainer>\n Container 2" as cont2
    }
    rectangle "volumes:" as volumes {
        rectangle "<$cm>\nConfigMap" as cm
        rectangle "<$secret>\n  Secret" as sec
    }
pod -- volumes : mount
cont1 -- cm : use
cont2 -- sec : use
legend left
TITLE
|= Component |= Definition |
|     <$vol> | **Volume** is a directory containing data,\n accesible to containers in a pod. |
|     <$secret> | **Secret** i a special type of storage containing a small\n amount of sensitive data such as a password, a token, or a key |
|     <$cm> | **Config Map** i a special type of storage that allows you to\n decouple environment-specific configuration from your container images |
endlegend
@enduml