@startuml MKE-UCP-Architecture
!include <kubernetes/k8s-sprites-labeled-25pct>
!include <tupadr3/devicons/docker>
!include <tupadr3/font-awesome/server>
rectangle "<color:black><$master></color> Mirantis Kubernetes Engine (former UCP) Architecture <color:blue><$k8s></color>\n" as tit

skinparam monochrome true
skinparam style strictuml
skinparam componentShadowing true
skinparam rectangleRoundCorner 35
skinparam rectangleBorderStyle dashed
skinparam linetype ortho

rectangle "Nodes" as nodes {
    node "Manager Node\n<$server>" as master {
        rectangle "   <$docker>\nucp-agent" as u1
        rectangle "   <$docker>\nucp-controller" as cont
        rectangle "   <$docker>\nucp-auth-api" as auth
        collections "          <$docker>\nother-components" as other
    }
    node "Worker Node\n<$server>" as worker1 {
        rectangle "   <$docker>\nucp-agent" as u2
        rectangle "   <$docker>\nucp-proxy" as prox1
    }
    node "Worker Node\n<$server>" as worker2 {
        rectangle "   <$docker>\nucp-agent" as u3
        rectangle "   <$docker>\nucp-proxy" as prox2
    }
}
tit -[hidden]-nodes

legend left
 |= Component |= Description |= Function  |
 |     ucp-agent  | Globally scheduled service \n (runs on every node) | Node monitoring, different behavior \n depending if it runs on manager or worker node |
endlegend

@enduml