@startuml multicloud-styles
'Icons
!include https://raw.githubusercontent.com/Piotr1215/sprites/master/rest-api.puml
!include <azure/AzureCommon.puml>
!include <kubernetes/k8s-sprites-labeled-25pct>
!include <aws/Compute/AmazonECS/ECScontainer/ECScontainer>
!include <tupadr3/devicons/docker>
!include <azure/Web/AzureWebApp.puml>
!include <azure/Compute/AzureFunction.puml>
!include <tupadr3/font-awesome/server>
!include <tupadr3/font-awesome/chrome>
!include <tupadr3/font-awesome/terminal>
!include <tupadr3/font-awesome/building>
!include <tupadr3/font-awesome/database>
!include <logos/azure.puml>
!include <logos/google-cloud.puml>
!include <logos/jenkins.puml>
!include <logos/github.puml>
!include <logos/salesforce.puml>
!include <logos/kubernetes.puml>
!include <logos/dropbox.puml>
'Global Styles
!include https://raw.githubusercontent.com/Piotr1215/dca-prep-kit/master/diagrams/styles.iuml
'Overrides
skinparam linetype default
skinparam rectangleBorderStyle solid
skinparam Shadowing true

<style>
cloud <<saas>> {
  HorizontalAlignment center
}
database {
  HorizontalAlignment center
}
</style>
@enduml
