@startuml MKE-UCP-Architecture
'Icons
!include https://raw.githubusercontent.com/Piotr1215/sprites/master/rest-api.puml
!include <azure/AzureCommon.puml>
!include <kubernetes/k8s-sprites-labeled-25pct>
!include <aws/Compute/AmazonECS/ECScontainer/ECScontainer>
!include <tupadr3/devicons/docker>
!include <azure/Web/AzureWebApp.puml>
!include <azure/Compute/AzureFunction.puml>
!include <tupadr3/font-awesome/server>
!include <tupadr3/font-awesome/chrome>
!include <tupadr3/font-awesome/terminal>
!include <tupadr3/font-awesome/building>
!include <tupadr3/font-awesome/database>
!include <logos/azure.puml>
!include <logos/google-cloud.puml>
!include <logos/jenkins.puml>
!include <logos/github.puml>
!include <logos/salesforce.puml>
!include <logos/kubernetes.puml>
!include <logos/dropbox.puml>
'Global Styles
!include https://raw.githubusercontent.com/Piotr1215/dca-prep-kit/master/diagrams/styles.iuml
'Overrides
'skinparam linetype default
skinparam rectangleBorderStyle solid
skinparam Shadowing true

title Multi Cloud: vendor lockin

!$ab = "foo1"

cloud "<$azure>\nPublic Cloud" as azure {
    rectangle "PaaS\n<$AzureWebApp*0.7>" as webapp_azure
    rectangle "FaaS\n<$AzureFunction*0.75>" as function_azure
    rectangle "CaaS\n<$ECScontainer>" as container_azure
    rectangle "DaaS\n<$database>" as db_azure
    rectangle "IaaS\n<$server>" as vm_azure
    rectangle "PaaS/IaaS\n<$kubernetes>" as k8s_azure
}

cloud "<$google-cloud>\nPublic Cloud" as gcp {
    rectangle "PaaS\n<$AzureWebApp*0.7>" as webapp_gpc
    rectangle "FaaS\n<$AzureFunction*0.75>" as function_gpc
    rectangle "CaaS\n<$ECScontainer>" as container_gpc
    rectangle "DaaS\n<$database>" as db_gpc
    rectangle "IaaS\n<$server>" as vm_gcp
    rectangle "PaaS/IaaS\n<$kubernetes>" as k8s_gcp
}

rectangle "<$building>\nPrivate Cloud" as prem {
    rectangle "<$server>" as vm_prem{
        rectangle "<$database>" as db_prem
    }
    rectangle "<$kubernetes>" as k8s_prem {
        rectangle "<$ECScontainer>" as container_prem
        rectangle "<$AzureFunction*0.75>" as function_prem
        rectangle "<$AzureWebApp*0.7>" as webapp_prem

    }
}

cloud "SaaS" as saas {
    rectangle "<$dropbox>"
    rectangle "<$salesforce>"
}

@enduml