@startuml
!theme cerulean-outline

'!pragma layout elk
skinparam DefaultFontSize 16
skinparam BackgroundColor white
'skinparam LineType ortho
'scale 1024 width
'scale 768 height

interface "HTTPS" as source_interface
rectangle "Flux Infrastructure Repo" as flux {
    file "EC2 Git\nSource YAML" as source

    file "K8s Resources\nKustomization YAML" as kusto
}
rectangle "EC2 Instance Repo" as ec2 {
file "K8s or Helm files" as files
}

ec2 --> source_interface
source_interface ..(0 source

kusto o- source

kusto .. files


''==Bootstrap Repository== 
'group Bootstrap
'dev -> repo : Create a repository from\ntemplate and trigger CI
'box "K8s Cluster"
'    participant "Flux" as flux
'    participant "Crossplane" as crossplane
'end box
'repo -> flux : Register repo as Source
'flux -> flux : Create base Kustomization\nfrom template folder
'end
'
'group Create Cloud Resources
'    flux -> crossplane : Push base claims to the cluster
'    participant "Cloud Resources" as cloud_infra
'    crossplane -> cloud_infra : Build base infrastructure\nwith Crossplane 
'end group
'
'dev <--- cloud_infra : Consume cloud resources
'note left of cloud_infra
'    Developers can provision more resources
'    by creating claims in a designated folder
'    and pushing changes to the remote repo.
'end note
@enduml
